//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> LeaveStartDate { get; set; }
        public Nullable<System.DateTime> LeaveEndDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> TotalLeaveDaysTaken { get; set; }
        public Nullable<int> TotalLeaveLeft { get; set; }
        public string ThemeColor { get; set; }
        public string IsFullDay { get; set; }
        public string LeaveType { get; set; }
    }
}
